### ISSUE TITLE
No Emojis when running either Uptime.exe or Uptime.py

### ISSUE THREAD

**Issue by TGDavid69** [zero-stroke/uptime#1]
Hi. I'm enjoying the script. However, I'd like to see the emojis that you show in the preview/example log. 
![dwqdwqq](https://github.com/user-attachments/assets/f32dda90-04a7-47b3-9f2d-9bcf3392a39e)

This is what I see.

**Comment by zero-stroke** [comment]
I tried running this on different VM's and this seems to be a problem with windows 10. New release should have fixed this by replacing the emojis with more cmd friendly symbols. 

![Screenshot 2024-10-21 155121](https://github.com/user-attachments/assets/5f16796d-466e-4e72-8c25-44b27a292369)

**Comment by TGDavid69** [comment]
> I tried running this on different VM's and this seems to be a problem with windows 10. New release should have fixed this by replacing the emojis with more cmd friendly symbols.
> 
> ![Screenshot 2024-10-21 155121](https://private-user-images.githubusercontent.com/57886710/378577712-5f16796d-466e-4e72-8c25-44b27a292369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjMwNTUsIm5iZiI6MTcyOTU2Mjc1NSwicGF0aCI6Ii81Nzg4NjcxMC8zNzg1Nzc3MTItNWYxNjc5NmQtNDY2ZS00ZTcyLThjMjUtNDRiMjdhMjkyMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YWY3MzdhODUxY2MzYmI1MjcwZTBkNDZjZjE3ZjgzMWE4N2ZjMGQ1Y2IyMjE0ZDU0OGJjYjQzYWFkMjYxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iAHBOQ82s6vCqwD0K6jC-nIrUOCwj78bh0OPDpMN2R4)

Cool!!! Thank you very much for this script :) it works great and doesn't seem to impact my gaming at all <3
